### ISSUE TITLE
Trying to run demo, gives invalid escape sequence error on startup

### ISSUE THREAD

**Issue by Nedok** [luapower/ui#2]
Using luajit on windows 10.

Running command:
`luajit ui.lua`
Results in:
`lua: ui.lua:4629: invalid escape sequence near '''`
The line that cast the error is:
`layer.paragraph_separator = '\u{2029}' --PS`

I have run the `ui_demo_bundle.bat`.
Used mgit to download everything of luapower using there "How do I get started?" instructions.

I can not figure out why i get the error...

**Comment by capr** [comment]
Unicode escape sequences were added in LuaJIT 2.1. Seems like you're using LuaJIT 2.0. Either convert the code or use the latest LuaJIT.

**Comment by Nedok** [comment]
Updated LuaJIT to 2.1-beta3 fix it.
Thank you :)
